server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 10MB
      max-request-size: 100MB
  #数据库连接配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_secondhandtrade?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
  mail:
    host: smtp.qq.com
    username: 111@qq.com
    password: 11
    default-encoding: UTF-8
    protocol: smtp
    properties:
      mail:
        smtp:
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
          ssl:
            enable: true #一定要开启ssl,不然会503 验证失败的（开启加密验证）
  redis:
    database: 0
    host: 121.11.11.106
    password: 11
    port: 6379
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  # 如果是放在src/main/java目录下 classpath:/com/*/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/**.xml
  mapper-locations: classpath:/mapper/**.xml

#客户头像图片存储地址
userImageFilePath: E://MyProject/IDEA/ActualCombat/SecondHandTrade/src/main/webapp/static/images/userImage/
#轮播图图片存储地址
carouselImageFilePath: E://MyProject/IDEA/ActualCombat/SecondHandTrade/src/main/webapp/static/images/carouselImage/
#公告或商品详情图片存储地址
articleImageFilePath: E://MyProject/IDEA/ActualCombat/SecondHandTrade/src/main/webapp/static/images/articleImage/
#求购类别的id
wantToBuyId: 8