server:
  port: 80
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0
      max-file-size: 10MB
      max-request-size: 100MB
  #Database connection configuration
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_secondhandtrade?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
    username: root
    password: root
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  thymeleaf:
    cache: false
  mail:
    host: smtp.qq.com
    username: 111@qq.com
    password: 11
    default-encoding: UTF-8
    protocol: smtp
    properties:
      mail:
        smtp:
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
          ssl:
            enable: true #Be sure to turn on ssl, otherwise 503 verification will fail (turn on encryption verification)
  redis:
    database: 0
    host: 127.0.0.1
    password: redis # set the password first 先配置redis密码 redis, 不是12345
    port: 6379
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  # 如果是放在src/main/java目录下 classpath:/com/*/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/**.xml
  mapper-locations: classpath:/mapper/**.xml

#Customer avatar image storage address D://sem6/WIA3003/SecondHandTrade/src/main/webapp/static
userImageFilePath: D://sem6/WIA3003/SecondHandTrade/src/main/webapp/static/images/userImage/
#Carousel image storage address
carouselImageFilePath: D://sem6/WIA3003/SecondHandTrade/src/main/webapp/static/images/carouselImage/
#Announcement or product details image storage address
articleImageFilePath: D://sem6/WIA3003/SecondHandTrade/src/main/webapp/static/images/articleImage/
#The id of the purchase category
wantToBuyId: 8